; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;set default_envs to whichever board(s) you use. Build/Run/etc processes those envs
default_envs =
   esp32dev

[env]
; Global data for all [env:***]
framework = arduino
lib_ldf_mode = deep
monitor_speed = 115200
upload_speed = 921600
lib_deps =
   SignalK/SensESP@^3.5.0

[espressif32_base]
;this section has config items common to all ESP32 boards
platform = espressif32 @ ^7.1.0
build_unflags = -Werror=reorder
board_build.partitions = min_spiffs.csv
monitor_filters = esp32_exception_decoder
extra_scripts = pre:platformio_version_increment/version_increment_pre.py
	            ;post:platformio_version_increment/esp32_create_factory_bin_post.py
				    post:platformio_version_increment/version_increment_post.py
build_flags =
   ; Max (and default) debugging level in Arduino ESP32 Core
   -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE
   ; Arduino Core bug workaround: define the log tag for the Arduino
   ; logging macros.
   -D TAG='"Arduino"'
   ; Use the ESP-IDF logging library - required by SensESP v3.
   -D USE_ESP_IDF_LOG

[env:esp32dev]
extends = espressif32_base
board = esp32dev
build_flags =
   ${espressif32_base.build_flags}
   -D LED_BUILTIN=2
   ; Uncomment the following to disable debug output altogether
   ;-D DEBUG_DISABLED
   ; Uncomment the following to enable the remote debug telnet interface on port 23
   ;-D REMOTE_DEBUG
; Uncomment the following to use the OTA interface for flashing.
; "mydevice" must correspond to the device hostname.
; "mypassword" must correspond to the device OTA password.
;upload_protocol = espota
;upload_port = SensESP-PeetBrosWind.local
;upload_flags =
;   --auth=mypassword